const $ = id => document.getElementById(id);
const saved = JSON.parse(localStorage.getItem('viral-ai-tool-state') || '{}');
const state = {
  page: saved.page || 'dashboard',
  output: saved.output || '',
  jobs: saved.jobs || [
    {name:'Douyin_Product_042.mp4',lang:'Vietnamese',status:'Processing',progress:73,time:'2 min ago'},
    {name:'UGC_Beauty_118.mp4',lang:'Korean',status:'Completed',progress:100,time:'18 min ago'},
    {name:'Review_Camera_090.mp4',lang:'English',status:'Completed',progress:100,time:'41 min ago'},
    {name:'Short_Fashion_031.mp4',lang:'Vietnamese',status:'Queued',progress:0,time:'1 hr ago'}
  ]
};
const nav = [
  ['WORKSPACE'],['dashboard','⌂','Dashboard'],['download','⇩','Download'],['monitor','◉','Channel Monitor','8'],
  ['CREATE'],['ai-video','✦','AI Video'],['voice','◖','Voice Studio'],['editor','◫','Video Editor'],['automation','⚡','Automation'],
  ['MANAGE'],['library','▦','Library'],['accounts','◎','Social Accounts'],['usage','◔','Usage & Credits'],['settings','⚙','Settings']
];
const titles = {dashboard:'Dashboard',download:'Download Studio',monitor:'Channel Monitor','ai-video':'AI Video',voice:'Voice Studio',editor:'Video Editor',automation:'Automation',library:'Library',accounts:'Social Accounts',usage:'Usage & Credits',settings:'Settings'};
function save(){localStorage.setItem('viral-ai-tool-state',JSON.stringify({page:state.page,output:state.output,jobs:state.jobs.slice(0,50)}));}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>t.classList.remove('show'),2200);}
function status(s){const c=s==='Completed'?'success':s==='Processing'?'processing':s==='Queued'?'warn':'error';return '<span class="badge '+c+'">'+s+'</span>';}
function jobsTable(rows=state.jobs){return '<div class="card table-wrap"><table class="data-table"><thead><tr><th>VIDEO</th><th>LANGUAGE</th><th>STATUS</th><th>PROGRESS</th><th>UPDATED</th></tr></thead><tbody>'+rows.map(j=>'<tr><td><div class="video-cell"><div class="thumb">▶</div><div>'+j.name+'</div></div></td><td>'+j.lang+'</td><td>'+status(j.status)+'</td><td>'+j.progress+'%</td><td>'+j.time+'</td></tr>').join('')+'</tbody></table></div>';}
function navRender(){const n=$('nav');n.innerHTML='';nav.forEach(i=>{if(i.length===1){n.insertAdjacentHTML('beforeend','<div class="nav-group">'+i[0]+'</div>');return;}n.insertAdjacentHTML('beforeend','<button class="nav-item '+(state.page===i[0]?'active':'')+'" data-page="'+i[0]+'"><span class="nav-icon">'+i[1]+'</span><span>'+i[2]+'</span>'+(i[3]?'<span class="nav-badge">'+i[3]+'</span>':'')+'</button>');});}
function dashboard(){return '<div class="hero"><div class="hero-copy"><div class="eyebrow">AI CONTENT OPERATING SYSTEM</div><h2>Create, localize and publish video at scale.</h2><p>Một phần mềm desktop để nhập video, dịch, tạo voice AI, subtitle, render và tự động hóa quy trình.</p><div class="hero-actions"><button class="button primary" data-page="ai-video">✦ Create AI video</button><button class="button ghost" data-page="download">⇩ Import video</button></div></div></div><div class="stat-grid">'+[['Videos today','24','+18% vs yesterday'],['Processing','3','2 rendering · 1 queued'],['Completed','218','This month'],['AI minutes','1,482','of 2,000 min']].map((x,i)=>'<div class="stat-card"><div class="stat-label">'+x[0]+'</div><div class="stat-value">'+x[1]+'</div><div class="stat-foot '+(i===0?'up':'')+'">'+x[2]+'</div></div>').join('')+'</div><div class="section-head"><div><h3>Quick tools</h3><p>Đi thẳng vào tác vụ thường dùng.</p></div></div><div class="tool-grid">'+[['↯','Translate video','Speech → translation → dubbing','ai-video'],['◖','AI Voice','TTS, voice library & cloning','voice'],['▤','Auto subtitle','Generate, style & burn captions','editor'],['⇩','Download','Import URL or files','download']].map(x=>'<div class="tool-card" data-page="'+x[3]+'"><div class="tool-icon">'+x[0]+'</div><h4>'+x[1]+'</h4><p>'+x[2]+'</p></div>').join('')+'</div><div class="section-head"><div><h3>Recent jobs</h3><p>Realtime processing status.</p></div></div>'+jobsTable();}
function download(){return '<div class="grid-2"><div class="card card-pad"><div class="eyebrow">IMPORT BY URL</div><h3>Download source video</h3><p class="muted">Dán URL nội dung bạn có quyền sử dụng. Engine tải thật sẽ nối ở bước backend.</p><div class="row"><input id="url" class="input" placeholder="https://..."><button id="analyze" class="button primary">Analyze URL</button></div><div class="platforms">'+['TikTok','Douyin','YouTube','Bilibili','Facebook','Instagram','Xiaohongshu'].map(x=>'<span class="platform">'+x+'</span>').join('')+'</div></div><div class="card card-pad"><div class="eyebrow">LOCAL FILES</div><h3>Import from your computer</h3><p class="muted">Chọn nhiều video hoặc kéo thả trực tiếp từ Windows Explorer.</p><div id="dropzone" class="dropzone"><div class="dropzone-icon">⇧</div><strong>Click or drop videos here</strong><p>MP4 · MOV · MKV · WEBM · AVI · M4V</p></div></div></div><div class="section-head"><div><h3>Import queue</h3><p>Video đã thêm vào workspace.</p></div></div>'+jobsTable();}
function monitor(){return '<div class="hero"><div class="hero-copy"><div class="eyebrow">CHANNEL AUTOMATION</div><h2>Detect new uploads automatically.</h2><p>Theo dõi nguồn đã cấu hình và tạo job khi có nội dung mới phù hợp.</p><div class="hero-actions"><button id="addChannel" class="button primary">＋ Add channel</button></div></div></div><div class="section-head"><div><h3>Monitored channels</h3><p>Prototype trạng thái theo dõi.</p></div></div><div class="card">'+[['Beauty Daily','Douyin','12 videos','on'],['Review Lab','TikTok','6 videos','on'],['Camera Zone','YouTube','3 videos','']].map(x=>'<div class="automation-card"><div class="auto-icon">◉</div><div class="auto-copy"><b>'+x[0]+' · '+x[1]+'</b><p>'+x[2]+' detected this week · Check every 30 min</p></div><div class="switch '+x[3]+'"></div></div>').join('')+'</div>';}
function aiVideo(){return '<div class="section-head"><div><h3>Localization workflow</h3><p>Source → speech → translate → voice → subtitle → render.</p></div><button id="render" class="button primary">Render final</button></div><div class="workflow">'+[['1','Import','Ready'],['2','Speech','Detected'],['3','Translate','Vietnamese'],['4','Voices','2 speakers'],['5','Subtitles','Styled'],['6','Render','Pending']].map((x,i)=>'<div class="wf-step '+(i===3?'active':'')+'"><b>'+x[0]+'. '+x[1]+'</b><span>'+x[2]+'</span></div>'+(i<5?'<div class="wf-arrow">→</div>':'')).join('')+'</div><div class="section-head"><div><h3>Project editor</h3><p>Product_review_042</p></div></div><div class="editor-grid"><div class="preview"><div class="preview-center"><div class="preview-play">▶</div><div class="preview-label">00:24 / 01:18 · Localized preview</div></div></div><div class="stack"><div class="mini-card"><h4>Translation</h4><label class="label">Target language</label><select class="select"><option>Vietnamese</option><option>English</option><option>Korean</option><option>Japanese</option></select><div class="toggle-row"><span>Preserve tone</span><div class="toggle on"></div></div><div class="toggle-row"><span>Translate on-screen text</span><div class="toggle on"></div></div></div><div class="mini-card"><h4>Output</h4><select class="select"><option>9:16 · 1080×1920</option><option>16:9 · 1920×1080</option><option>1:1 · 1080×1080</option></select><div class="toggle-row"><span>Burn subtitles</span><div class="toggle on"></div></div></div></div></div>';}
function voice(){const wave=()=>Array.from({length:22},(_,i)=>'<i style="height:'+(7+(i*11)%17)+'px"></i>').join('');return '<div class="grid-2"><div class="card card-pad"><div class="eyebrow">TEXT TO SPEECH</div><h3>Generate voice preview</h3><textarea class="textarea" rows="6">Chào mừng bạn đến với Viral AI Tool. Đây là bản demo giọng đọc cho video của bạn.</textarea><div class="row" style="margin-top:8px"><select class="select"><option>Minh · Vietnamese</option><option>Vy · Vietnamese</option><option>Ava · English</option></select><button id="tts" class="button primary">Generate</button></div></div><div class="card card-pad"><div class="eyebrow">VOICE CLONE</div><h3>Create your own voice</h3><p class="muted">Chỉ dùng sample có sự đồng ý của chủ giọng nói.</p><div class="dropzone"><div class="dropzone-icon">◖</div><strong>Upload consented sample</strong><p>WAV / MP3 · 1–5 minutes</p></div></div></div><div class="section-head"><div><h3>Voice library</h3></div></div><div class="voice-grid">'+[['Minh','Vietnamese · Male','M'],['Vy','Vietnamese · Female','V'],['Jisoo','Korean · Female','J'],['Haruto','Japanese · Male','H'],['Ava','English · Female','A'],['Noah','English · Male','N']].map(x=>'<div class="voice-card"><div class="voice-top"><div class="voice-avatar">'+x[2]+'</div><div class="voice-meta"><b>'+x[0]+'</b><span>'+x[1]+'</span></div></div><div class="wave">'+wave()+'</div><button class="button ghost small previewVoice">▶ Preview</button></div>').join('')+'</div>';}
function editor(){return '<div class="editor-grid"><div class="preview"><div class="preview-center"><div class="preview-play">▶</div><div class="preview-label">Video canvas · 1080×1920</div></div></div><div class="stack"><div class="mini-card"><h4>Subtitle</h4><div class="toggle-row"><span>Auto captions</span><div class="toggle on"></div></div><div class="toggle-row"><span>Highlight keywords</span><div class="toggle on"></div></div></div><div class="mini-card"><h4>Video</h4><label class="label">Aspect ratio</label><select class="select"><option>9:16 Vertical</option><option>16:9 Landscape</option></select><div class="toggle-row"><span>Normalize audio</span><div class="toggle on"></div></div></div><button id="export" class="button primary">Export video</button></div></div>';}
function automation(){return '<div class="grid-3"><div class="stat-card"><div class="stat-label">Active workflows</div><div class="stat-value">3</div></div><div class="stat-card"><div class="stat-label">Runs this month</div><div class="stat-value">486</div></div><div class="stat-card"><div class="stat-label">Time saved</div><div class="stat-value">31h</div></div></div><div class="section-head"><div><h3>Workflow automations</h3></div><button id="newFlow" class="button primary">＋ New workflow</button></div><div class="card">'+[['Auto Localize','New source → dubbing → subtitle → render','on'],['Auto Publish','Completed render → publish','on'],['Failed Job Retry','Retry failures up to 3 times','on'],['Archive Old Files','Move sources older than 30 days','']].map(x=>'<div class="automation-card"><div class="auto-icon">⚡</div><div class="auto-copy"><b>'+x[0]+'</b><p>'+x[1]+'</p></div><div class="switch '+x[2]+'"></div></div>').join('')+'</div>';}
function library(){return '<div class="section-head"><div><h3>Video library</h3><p>Source, processing và rendered outputs.</p></div><input id="search" class="input" style="width:220px" placeholder="Search video..."></div><div id="libraryTable">'+jobsTable()+'</div>';}
function accounts(){return '<div class="section-head"><div><h3>Publishing accounts</h3><p>Kết nối tài khoản dùng trong workflow xuất bản.</p></div></div><div class="grid-2">'+[['TikTok','@hoangstudio','Connected'],['YouTube','Hoang Studio','Connected'],['Instagram','@hoang.creates','Connected'],['Facebook','Not connected','Connect']].map(x=>'<div class="card card-pad"><div class="row" style="justify-content:space-between"><div><div class="eyebrow">'+x[0]+'</div><b>'+x[1]+'</b></div><button class="button '+(x[2]==='Connected'?'ghost':'primary')+' account">'+x[2]+'</button></div></div>').join('')+'</div>';}
function usage(){return '<div class="grid-2"><div class="card card-pad"><div class="eyebrow">CURRENT PLAN</div><h3>Creator Pro</h3><p class="muted">2,480 credits remaining · Renews Oct 18, 2026</p><button class="button primary">Upgrade plan</button></div><div class="card card-pad"><div class="eyebrow">MONTHLY USAGE</div><div class="stat-value">1,520 / 4,000</div><div class="bar"><i style="width:38%"></i></div></div></div><div class="section-head"><div><h3>Usage breakdown</h3></div></div><div class="usage-grid">'+[['AI dubbing','620'],['Render minutes','410'],['Downloads','286'],['Automation runs','204']].map(x=>'<div class="stat-card"><div class="stat-label">'+x[0]+'</div><div class="stat-value">'+x[1]+'</div></div>').join('')+'</div>';}
function settings(){return '<div class="grid-2"><div class="card card-pad"><div class="eyebrow">GENERAL</div>'+[['Project autosave','Save changes automatically','on'],['GPU render queue','Use acceleration when available','on'],['Email notifications','Notify when render finishes',''],['Compact sidebar','Reduce navigation spacing','']].map(x=>'<div class="setting-row"><div class="setting-copy"><b>'+x[0]+'</b><span>'+x[1]+'</span></div><div class="switch '+x[2]+'"></div></div>').join('')+'</div><div class="card card-pad"><div class="eyebrow">OUTPUT</div><label class="label">Output folder</label><div class="row"><input id="outputPath" class="input" readonly value="'+(state.output||'Not selected')+'"><button id="chooseOutput" class="button ghost">Choose</button></div><div style="margin-top:14px"><label class="label">Resolution</label><select class="select"><option>1080p</option><option>4K</option></select></div></div></div>';}
const pages={dashboard,download,monitor,'ai-video':aiVideo,voice,editor,automation,library,accounts,usage,settings};
function render(){navRender();$('pageTitle').textContent=titles[state.page];$('breadcrumb').textContent='Workspace / '+titles[state.page];$('page').innerHTML=pages[state.page]();bind();save();}
function modal(title,body){const m=$('modal');m.classList.remove('hidden');m.innerHTML='<div class="modal"><div class="eyebrow">VIRAL AI TOOL</div><h3>'+title+'</h3><p>'+body+'</p><div class="modal-actions"><button id="cancel" class="button ghost">Cancel</button><button id="ok" class="button primary">Create</button></div></div>';$('cancel').onclick=()=>m.classList.add('hidden');$('ok').onclick=()=>{m.classList.add('hidden');toast(title+' created');};}
async function addFiles(){if(!window.desktopAPI)return;const files=await window.desktopAPI.selectVideos();if(!files.length)return;files.forEach(f=>state.jobs.unshift({name:f.name,lang:'Not set',status:'Queued',progress:0,time:'Now',sourcePath:f.path}));render();toast(files.length+' video(s) added');}
function simulateRender(){const j={name:'viral_ai_output_'+Date.now()+'.mp4',lang:'Vietnamese',status:'Processing',progress:5,time:'Now'};state.jobs.unshift(j);render();let p=5;const timer=setInterval(()=>{p+=Math.floor(Math.random()*13)+5;j.progress=Math.min(100,p);if(j.progress>=100){j.status='Completed';clearInterval(timer);toast('Render completed');}save();if(state.page==='library'||state.page==='dashboard'||state.page==='download')render();},850);}
function bind(){document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{state.page=x.dataset.page;render();});document.querySelectorAll('.switch,.toggle').forEach(x=>x.onclick=()=>x.classList.toggle('on'));document.querySelectorAll('.previewVoice').forEach(x=>x.onclick=()=>toast('Playing voice preview…'));document.querySelectorAll('.account').forEach(x=>x.onclick=()=>toast(x.textContent==='Connected'?'Account already connected':'Connection flow will be added next'));
const dz=$('dropzone');if(dz)dz.onclick=addFiles;const a=$('analyze');if(a)a.onclick=()=>toast($('url').value.trim()?'URL analyzed · downloader engine is next':'Paste a URL first');const r=$('render');if(r)r.onclick=simulateRender;const t=$('tts');if(t)t.onclick=()=>toast('Voice preview generated');const e=$('export');if(e)e.onclick=simulateRender;const c=$('addChannel');if(c)c.onclick=()=>modal('Add monitored channel','Connect a source channel and choose how often Viral AI Tool should check it.');const f=$('newFlow');if(f)f.onclick=()=>modal('New automation','Choose a trigger, processing steps and an optional publishing destination.');const s=$('search');if(s)s.oninput=()=>{$('libraryTable').innerHTML=jobsTable(state.jobs.filter(j=>j.name.toLowerCase().includes(s.value.toLowerCase())));};const o=$('chooseOutput');if(o)o.onclick=async()=>{const p=await window.desktopAPI?.selectOutputFolder();if(p){state.output=p;render();toast('Output folder saved');}};}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){state.page=p.dataset.page;render();}});
$('quickProject').onclick=()=>{state.page='ai-video';render();};
if(window.desktopAPI){$('winMin').onclick=()=>window.desktopAPI.minimize();$('winMax').onclick=()=>window.desktopAPI.toggleMaximize();$('winClose').onclick=()=>window.desktopAPI.close();document.addEventListener('dragover',e=>{e.preventDefault();document.body.classList.add('dragging');});document.addEventListener('dragleave',()=>document.body.classList.remove('dragging'));document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');const files=[...(e.dataTransfer?.files||[])].filter(f=>/\.(mp4|mov|mkv|webm|avi|m4v)$/i.test(f.name));if(!files.length)return;files.forEach(f=>state.jobs.unshift({name:f.name,lang:'Not set',status:'Queued',progress:0,time:'Now',sourcePath:f.path}));render();toast(files.length+' dropped video(s) added');});}
render();
